# Use root/example as user/password credentials
version: '3.1'

services:
    custom_mysql_cont:
        image: custom_mysql_image
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
          MYSQL_ROOT_PASSWORD: examplepassword
        ports:
          - 8080:3306
        